### ISSUE TITLE
ColorTabs causing other extensions rendering to disappear

### ISSUE THREAD

**Issue by Yzrsah** [oreporan/color-tabs-vscode#7] opened 2019-03-13 23:45 UTC
ColorTabs causes a flicker and extra redraw of the editor when you change tabs.
This makes other extensions disappear from the editor.

To Reproduce:
- Enable ColorTabs extension with titleBackground or tabBorder
- Install [ErrorLens](https://marketplace.visualstudio.com/items?itemName=PhilHindle.errorlens) extension
- Open an file that has some errors or warnings
- Switch between tabs
- ErrorLens disappears when ColorTabs forces redraw

**Comment by oreporan** [comment] 2019-03-14 09:41
@Yzrsah 
I'll investigate this, thanks
Did you notice if this redraw also happens when only the titleBar feature is turned on?

`"colorTabs.titleLabel": true`
`"colorTabs.titleLabel": false`

**Comment by oreporan** [comment] 2019-03-14 10:44
@Yzrsah I'll investigate this
Thanks

**Comment by Yzrsah** [comment] 2019-03-14 10:48
ColorTabs is a very useful extension for helping with MonoRepos. I hope the problem can be fixed. If it's not fixable we should ask Microsoft because it needs to work.

**Comment by Yzrsah** [comment] 2019-03-14 10:49
ColorTabs is a very useful extension for helping with MonoRepos. I hope the problem can be fixed. If it's not fixable we should ask Microsoft because there's a good use case for it needing to work.

**Comment by oreporan** [comment] 2019-03-14 10:51
I'm not able to reproduce...
Mine works smoothly, I'll upload a gif, though the gif itself might be a bit choppy...

**Comment by Yzrsah** [comment] 2019-03-14 10:52
Did you try on Insiders?

**Comment by oreporan** [comment] 2019-03-14 10:54
![delay_gif](https://user-images.githubusercontent.com/2146999/54351492-e5023a80-464f-11e9-91a1-a69c745d8121.gif)

**Comment by Yzrsah** [comment] 2019-03-14 10:57
That looks exactly correct. I'll investigate if there's something else going on

**Comment by oreporan** [comment] 2019-03-14 10:58
You see the error, then the error dissapears, color-tabs paints, and then the error re-apppears? Is that correct?

**Comment by Yzrsah** [comment] 2019-03-14 11:00
Yes

**Comment by Yzrsah** [comment] 2019-03-14 11:00
The error never re-appears

**Comment by oreporan** [comment] 2019-03-14 11:01
ah ok, thats very odd.
This extension doesn't touch the editor at all.
Do other extensions also dissapear?
You can try gitLens for example

**Comment by oreporan** [comment] 2019-03-14 11:02
This extension changes the `workbench.colorCustomizations` so its possible that somehow it overrides another colorCustomization made by Error Lens, I'll look

**Comment by Yzrsah** [comment] 2019-03-14 11:05
I do have customizations for the errorLens colors in settings

```
    "errorLens.errorColor": "rgba(240,10,0,0.25)",
    "errorLens.hintColor": "rgba(20,100,0,0.2)",
    "errorLens.infoColor": "rgba(240,200,0,0.2)",
    "errorLens.warningColor": "rgba(180,150,0,0.15)",
```

**Comment by oreporan** [comment] 2019-03-14 11:06
ahh ok so this could be it.
These are custom colors you added?

**Comment by Yzrsah** [comment] 2019-03-14 11:06
yes

**Comment by oreporan** [comment] 2019-03-14 11:08
ok I've tested, and these are not under `workspace.ColorCustomizations` so it should not conflict

**Comment by Yzrsah** [comment] 2019-03-14 11:10
I have a bunch of workspace.ColorCustomizations also

I just disabled them and now it's working

**Comment by oreporan** [comment] 2019-03-14 11:11
ok so there is an issue, you are right, this needs to be fixed

**Comment by Yzrsah** [comment] 2019-03-14 11:11
Thank you for figuring it out quick!

**Comment by oreporan** [comment] 2019-03-14 11:14
NP
The solution might be a bit more complicated.
Because I do grab the current colorCustomizations and append them back to the result, but I'm afraid this could be a race issue where at the time of appending, errorLens didn't set them yet.

**Comment by oreporan** [comment] 2019-03-14 11:19
but just with ErrorLens and ColorTabs - without other `colorCustomizations` do you still run into this issue?

**Comment by oreporan** [comment] 2019-03-14 11:23
To say the truth I've also added something to `colorCustomizations` manually (`"statusBar.background"`) and it still seems to work fine with ColorTabs + ErrorLens with custom colors + colorCustomization

So I guess it must be some race condition where sometimes it falls in the right order and sometimes it doesnt..

**Comment by oreporan** [comment] 2019-03-14 11:24
Top - ColorTabs set to yellow
Editor - ErrorLens - set to pink on errors
StatusBar - set to green in `colorCustomizations` 

<img width="1440" alt="Screen Shot 2019-03-14 at 12 24 13" src="https://user-images.githubusercontent.com/2146999/54353358-1aa92280-4654-11e9-881d-697bd235ffe9.png">

**Comment by oreporan** [comment] 2019-03-18 14:15
I'm going to close this since I couldn't reproduce

**Comment by Yzrsah** [comment] 2019-03-18 15:15
@oreporan I've had it on my Todo to answer your questions properly by isolating the setup. Didn't get enough free time yet

**Comment by Yzrsah** [comment] 2019-03-18 15:16
@oreporan 

> but just with ErrorLens and ColorTabs - without other `colorCustomizations` do you still run into this issue?

I've had it on my Todo to answer your questions properly by isolating the setup. Didn't get enough free time yet

**Comment by Yzrsah** [comment] 2019-03-18 15:21
@oreporan 

> but just with ErrorLens and ColorTabs - without other `colorCustomizations` do you still run into this issue?

The problem does not occur with `workbench.colorCustomizations` disabled.

I've had it on my Todo to answer your questions properly by isolating the setup. Didn't get enough free time yet

**Comment by Yzrsah** [comment] 2019-03-18 15:30
I will try to get this done in the next days, I need to remove everything from VSCode and test with your extension and ErrorLens only, then re-enable stuff until I find the problem. It can be troublesome doing that process because of VSCode issue 69090 (didn't post link cause of reference)

**Comment by oreporan** [comment] 2019-04-15 13:50
closing this for now

**Closed as completed by oreporan** 2019-04-15 13:50 UTC
Labels: bug

**Comment by Yzrsah** [comment] 2019-04-15 15:10
@oreporan 

I tested this by disabling and re-enabling extensions. An extension that I thought was causing it turned out to not be causing it when re-enabling other extensions. The results kept changing and it is unpredictable.

The bug also happens with all extensions disabled, depending on which type of tab you switch from: It happens when switching from an Extensions tab over to the editor tab.

The method of modifying the config file is error prone and latent.

I am sensitive to timing and this extension adds an extra update to rendering when switching tabs. This makes this extension unusable because it breaks a basic rule for extensions, which is that they cannot slow down VSCode. I have attempted to use the extension but the issues are too noticeable.

There is no way to solve the problem due to limitations of VSCode. But the much more important part is the idea, and you had a good idea which helps with real issues of the monorepo. I've "edited the wrong file in the wrong direcrtory" and felt foolish many times. It can get super confusing with all the nesting. This extension solves it in a simple way.

We should open and support a proper issue on the VSCode issue tracker in order to request the specific feature needed to allow for this functionality to be implemented without the side effects of modifying config files.

**Comment by Yzrsah** [comment] 2019-04-15 15:11
@oreporan 

I tested this by disabling and re-enabling extensions. An extension that I thought was causing it turned out to not be causing it when re-enabling other extensions. The results kept changing and it is unpredictable.

The bug also happens with all extensions disabled, depending on which type of tab you switch from: It happens when switching from an Extensions/Marketplace tab over to the editor tab.

The method of modifying the config file is error prone and latent.

I am sensitive to timing and this extension adds an extra update to rendering when switching tabs. This makes this extension unusable because it breaks a basic rule for extensions, which is that they cannot slow down VSCode. I have attempted to use the extension but the issues are too noticeable.

There is no way to solve the problem due to limitations of VSCode. But the much more important part is the idea, and you had a good idea which helps with real issues of the monorepo. I've "edited the wrong file in the wrong direcrtory" and felt foolish many times. It can get super confusing with all the nesting. This extension solves it in a simple way.

We should open and support a proper issue on the VSCode issue tracker in order to request the specific feature needed to allow for this functionality to be implemented without the side effects of modifying config files.

**Comment by oreporan** [comment] 2019-04-15 15:16
I wonder if the size of the file/project affects the re-rendering time...

So you're saying that if we could make color changes without affecting the `settings.json` in runtime then the re-renders would stop?

Thanks for the kind words :)

**Comment by Yzrsah** [comment] 2019-04-15 15:26
> So you're saying that if we could make color changes without affecting the `settings.json` in runtime then the re-renders would stop?

Yes that would fix. The feature request should be simple, something like "Ability to modify Theme colors without writing to config file". This extension makes an example of the exact use case for the feature.
